trigger: none

parameters:
- name: tag
  displayName: Image Tag
  type: string

variables:

- group: telegram-notifications

- name: AWS_REGION
  value: us-east-2

- name: REGISTRY
  value: 668384615068.dkr.ecr.us-east-2.amazonaws.com

stages:

# ========================
# UAT (SIN APPROVAL)
# ========================
- stage: UAT
  displayName: Deploy UAT
  jobs:
  - deployment: DeployUat
    displayName: Deploy to UAT
    environment: sisdep-back-uat
    strategy:
      runOnce:
        deploy:
          steps:
          - task: SSH@0
            inputs:
              sshEndpoint: 'EC2-SISDEP'
              runOptions: 'commands'
              commands: |
                set -e

                echo "===> Login to ECR"
                aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin $(REGISTRY) 2>/dev/null

                echo "===> Pulling image"
                docker pull $(REGISTRY)/sisdep-back:${{ parameters.tag }} 2>/dev/null

                echo "===> Updating service"
                docker service update --force --with-registry-auth --image $(REGISTRY)/sisdep-back:${{ parameters.tag }} sisdep-uat_back

                echo "===> Updating docker-stack.yml"
                TAG=${{ parameters.tag }} yq -i '.services.back.image |= sub(":[^:]+$", ":" + strenv(TAG))' /srv/app/sisdep-uat/docker-stack.yml

  - job: Notify_UAT
    displayName: Notify UAT

    dependsOn: DeployUat

    condition: always()

    variables:
      DEPLOY_STATUS: $[ dependencies.DeployUat.result ]

    steps:

    - template: DevOps/telegram-notify.yml
      parameters:
        type: DEPLOY
        environment: UAT
        status: $(DEPLOY_STATUS)
        tag: ${{ parameters.tag }}

# ========================
# QA (CON APPROVAL)
# ========================
- stage: QA
  displayName: Deploy QA
  dependsOn: UAT
  condition: succeeded()
  jobs:
  - deployment: DeployQA
    displayName: Deploy to QA
    environment: sisdep-back-qa 
    strategy:
      runOnce:
        deploy:
          steps:
          - task: SSH@0
            inputs:
              sshEndpoint: 'EC2-SISDEP'
              runOptions: 'commands'
              commands: |
                set -e

                echo "===> Login to ECR"
                aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin $(REGISTRY) 2>/dev/null

                echo "===> Pulling image"
                docker pull $(REGISTRY)/sisdep-back:${{ parameters.tag }} 2>/dev/null

                echo "===> Updating service"
                docker service update --force --with-registry-auth --image $(REGISTRY)/sisdep-back:${{ parameters.tag }} sisdep-qa_back

                echo "===> Updating docker-stack.yml"
                TAG=${{ parameters.tag }} yq -i '.services.back.image |= sub(":[^:]+$", ":" + strenv(TAG))' /srv/app/sisdep-qa/docker-stack.yml

  - job: Notify_QA
    displayName: Notify QA

    dependsOn: DeployQA

    condition: always()

    variables:
      DEPLOY_STATUS: $[ dependencies.DeployQA.result ]

    steps:

    - template: DevOps/telegram-notify.yml
      parameters:
        type: DEPLOY
        environment: QA
        status: $(DEPLOY_STATUS)
        tag: ${{ parameters.tag }}

# ========================
# PREPROD (CON APPROVAL)
# ========================
- stage: PREPROD
  displayName: Deploy PREPROD
  dependsOn: UAT
  condition: succeeded()
  jobs:
  - deployment: DeployPreprod
    displayName: Deploy to PREPROD
    environment: sisdep-back-preprod 
    strategy:
      runOnce:
        deploy:
          steps:
          - task: SSH@0
            inputs:
              sshEndpoint: 'EC2-SISDEP'
              runOptions: 'commands'
              commands: |
                set -e

                echo "===> Login to ECR"
                aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin $(REGISTRY) 2>/dev/null

                echo "===> Pulling image"
                docker pull $(REGISTRY)/sisdep-back:${{ parameters.tag }} 2>/dev/null

                echo "===> Updating service"
                docker service update --force --with-registry-auth --image $(REGISTRY)/sisdep-back:${{ parameters.tag }} sisdep_back

                echo "===> Updating docker-stack.yml"
                TAG=${{ parameters.tag }} yq -i '.services.back.image |= sub(":[^:]+$", ":" + strenv(TAG))' /srv/app/sisdep/docker-stack.yml

  - job: Notify_PREPROD
    displayName: Notify PREPROD

    dependsOn: DeployPreprod

    condition: always()

    variables:
      DEPLOY_STATUS: $[ dependencies.DeployPreprod.result ]

    steps:

    - template: DevOps/telegram-notify.yml
      parameters:
        type: DEPLOY
        environment: PREPROD
        status: $(DEPLOY_STATUS)
        tag: ${{ parameters.tag }}