# SonarQube - sivep-back
sonar.projectKey=sivep-back
sonar.projectName=sivep-back
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
